### ISSUE TITLE
this is tusky

### ISSUE THREAD

**Issue by Lana-chan** [hiveway/hiveway-android#2]
lmao you didn't even bother changing the filenames in the assets folder come on guys

https://github.com/tuskyapp/Tusky

**Comment by Lana-chan** [comment]
oh WOW ok nevermind i didn't realize it wasn't just the filenames, those are actual tusky assets still in this repo

this is an ever bigger issue and i think it should be marked urgent,

**Comment by devinacker** [comment]
are you telling me something cryptocurrency-related is actually fraudulent? jesus christ im shitting myself here

**Comment by Angristan** [comment]
Tusky? [What do you mean](https://github.com/hiveway/hiveway-android/search?q=tusky)

**Comment by tobypinder** [comment]
Given that this is GPL3 licensed software, I'm *sure* that the Hiveway community will act in good faith and follow the terms of that license, learning from their "mistakes" with Mastodon (ahem, Hiveway) itself.

**Comment by hiveway** [comment]
Added COPYRIGHT and changed the README.md file to clearly state it's a fork of Tusky.
